2020-09-12 09:54:30,112 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_项目名称长度1--执行成功
2020-09-12 09:54:30,465 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_项目名称长度200--执行成功
2020-09-12 09:54:30,580 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目名称长度0--执行成功
2020-09-12 09:54:30,798 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目名称长度201--执行成功
2020-09-12 09:54:31,016 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目名称重复--执行成功
2020-09-12 09:54:31,144 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_项目名称参数错误--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 35, in com_assertEqual
    com_assertIn(str(respone.json()), expect["msg"])  # msg
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 40, in com_assertIn
    raise AssertionError
AssertionError
2020-09-12 09:54:31,267 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目名称参数为空--执行成功
2020-09-12 09:54:31,593 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_项目负责人长度50--执行成功
2020-09-12 09:54:31,844 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_领导人参数错误--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 34, in com_assertEqual
    self.assertEqual(respone.status_code, expect["Status"])  # 判断code
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 201 != 400
2020-09-12 09:54:32,070 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_领导人长度0--执行成功
2020-09-12 09:54:32,288 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_领导人长度51--执行成功
2020-09-12 09:54:32,505 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_领导人参数为空--执行成功
2020-09-12 09:55:18,039 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_项目测试人长度50--执行成功
2020-09-12 09:55:18,259 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_项目测试人参数错误--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 34, in com_assertEqual
    self.assertEqual(respone.status_code, expect["Status"])  # 判断code
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 201 != 400
2020-09-12 09:55:18,489 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目测试人长度0--执行成功
2020-09-12 09:55:18,713 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目测试人长度51--执行成功
2020-09-12 09:55:18,939 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_项目测试人参数为空--执行成功
2020-09-12 09:55:19,269 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_项目开发人长度50--执行成功
2020-09-12 09:55:19,504 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_开发人参数错误--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 34, in com_assertEqual
    self.assertEqual(respone.status_code, expect["Status"])  # 判断code
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 201 != 400
2020-09-12 09:55:19,724 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_开发人参长度为0--执行成功
2020-09-12 09:55:19,948 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_开发人参长度为51--执行成功
2020-09-12 09:55:20,181 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_开发人参数为空--执行成功
2020-09-12 09:55:20,412 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_成功_发布应用长度100--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 34, in com_assertEqual
    self.assertEqual(respone.status_code, expect["Status"])  # 判断code
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 201 != 400
2020-09-12 09:55:20,675 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_发布应用参数错误--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 34, in com_assertEqual
    self.assertEqual(respone.status_code, expect["Status"])  # 判断code
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\64121\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 201 != 400
2020-09-12 09:55:20,897 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_发布应用参数长度为0--执行成功
2020-09-12 09:55:28,019 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_失败_发布应用参数长度为101--执行成功
2020-09-12 09:55:28,241 - [test_case_projects.py-->line:42] - ERROR: 用例--创建项目_失败_发布应用参数长度为空--执行失败
Traceback (most recent call last):
  File "c:\工具资料\GitHub\python_api_keyou\testcase\test_case_projects.py", line 35, in test_case
    com_assertEqual(self, respone, eval(kwargs["expect"]))
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 35, in com_assertEqual
    com_assertIn(str(respone.json()), expect["msg"])  # msg
  File "c:\工具资料\GitHub\python_api_keyou\com_func\com_request_func.py", line 40, in com_assertIn
    raise AssertionError
AssertionError
2020-09-12 09:55:28,576 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_简要描述长度200--执行成功
2020-09-12 09:55:28,900 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_简要描述长度0--执行成功
2020-09-12 09:55:29,227 - [test_case_projects.py-->line:46] - INFO: 用例--创建项目_成功_简要描述长度为空--执行成功
